{
 "title": "LAB_KMS",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - pykms_start_time_seconds{job=\"kms_job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KMS State Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 16, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "pykms_up{job=\"kms_job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "KMS Database Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pykms_database_size_bytes{job=\"kms_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KMS Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pykms_start_time_seconds{job=\"kms_job\"} * 1000",
     "legendFormat": "StartTime"
    }
   ]
  },
  {
   "title": "KMS Python Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pykms_info{job=\"kms_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Activation Time by Product",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pykms_database_last_activation_by_application{job=\"kms_job\"} * 1000",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Unique Clients in KMS Database",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 4 },
   "targets": [
    {
     "expr": "sum(pykms_clients_total{job=\"kms_job\"}) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "P95 Latency by Product",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (product, le) (rate(pykms_activation_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "KMS Build Tag",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pykms_info{job=\"kms_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Rate to KMS Database",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(pykms_database_total_requests{job=\"kms_job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique Success KMS Clients by SKU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pykms_activation_requests_total{job=\"kms_job\",status=\"success\"}",
     "legendFormat": "{{sku}}"
    }
   ]
  },
  {
   "title": "Unique Failure KMS Clients by SKU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pykms_activation_requests_total{job=\"kms_job\",status=\"failure\"}",
     "legendFormat": "{{sku}}"
    }
   ]
  },
  {
   "title": "Activation Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(pykms_activation_request_duration_seconds_sum{job=\"kms_job\"}) / rate(pykms_activation_request_duration_seconds_count{job=\"kms_job\"})) by (product)",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "Activations last 30s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "pykms_activations_last_30s{job=\"kms_job\"}",
     "legendFormat": "{{product}}_{{status}}"
    }
   ]
  },
  {
   "title": "Activations last 60s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "pykms_activations_last_60s{job=\"kms_job\"}",
     "legendFormat": "{{product}}_{{status}}"
    }
   ]
  },
  {
   "title": "Activations last 5m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "pykms_activations_last_300s{job=\"kms_job\"}",
     "legendFormat": "{{product}}_{{status}}"
    }
   ]
  },
  {
   "title": "Histogram Windows Activation Requests Duration by Hour",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (le) (rate(pykms_activation_request_duration_seconds_bucket{job=\"kms_job\",product=\"windows\"}[60m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Histogram Office Activation Requests Duration by Hour",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (le) (rate(pykms_activation_request_duration_seconds_bucket{job=\"kms_job\",product=\"office\"}[60m]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}